steps:
  - name: 'gcr.io/cloud-builders/git'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        LAST_TAG=$(gcloud artifacts docker tags list \
          asia-south1-docker.pkg.dev/organic-edge-475807-v2/myecp-repo/myecp-cloud \
          --format='value(TAG)' --sort-by=~CREATE_TIME --limit=1)

        if [[ -z "$LAST_TAG" ]]; then
          NEXT_TAG="v1.1.1"
        else
          BASE=$(echo $LAST_TAG | grep -oE '[0-9]+$')
          PREFIX=$(echo $LAST_TAG | sed 's/[0-9]\+$//')
          NEXT_NUM=$((BASE + 1))
          NEXT_TAG="${PREFIX}${NEXT_NUM}"
        fi

        echo "Next tag: $NEXT_TAG" 
        echo "$NEXT_TAG" > next_tag.txt

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "build",
        "-t",
        "asia-south1-docker.pkg.dev/organic-edge-475807-v2/myecp-repo/myecp-cloud:$(cat next_tag.txt)",
        "."
      ]

  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        "push",
        "asia-south1-docker.pkg.dev/organic-edge-475807-v2/myecp-repo/myecp-cloud:$(cat next_tag.txt)"
      ]

images:
  - "asia-south1-docker.pkg.dev/organic-edge-475807-v2/myecp-repo/myecp-cloud:$(cat next_tag.txt)"
